apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    service: app
  name: root
rules:
  - 
    apiGroups:
      - ""
      - apps
    resources:
      - pods
    verbs:
      - "*"
