apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    service: app
  name: rootbind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: root
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:default:default
