apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    service: monitor
  name: monitor
spec:
  storageClassName: app
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 512Mi
  hostPath:
    path: /var/tmp/app/kube/
    type: Directory
