apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: monitor
  name: monitor
spec:
  storageClassName: app
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      service: monitor
