apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  storageClassName: app
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  selector:
    matchLabels:
      service: nginx
